use std::fs;

/// Generate `src/finite_enum.rs` — anonymous zero-vtable enums for `finite_score_set!`.
///
/// Each `FiniteEnum{N}` wraps N heterogeneous metric types and dispatches
/// `eval`/`name` via `match` — zero vtable overhead.
///
/// Also generates the `IntoFiniteEntries` trait + per-arity impls so that
/// `finite_score_set!` can delegate to trait dispatch (like `fixed_score_set!`
/// delegates to `Members`), keeping the macro to a single arm.
pub fn generate(max: usize) {
    let out_dir = std::env::current_dir().unwrap();
    let out_path = out_dir.join("src").join("finite_enum.rs");

    assert!(max >= 1, "max must be >= 1");
    let default_level = default_level_for(max);
    let mut content = String::new();

    // ---- header ----
    content.push_str(&format!(
        "// @generated by xtask. Do not edit by hand.\n\
         // ---------------------------------------------------------------------------\n\
         // Anonymous zero-vtable enums for [`finite_score_set!`](crate::finite_score_set!).\n\
         //\n\
         // Each `FiniteEnum{{N}}` wraps N heterogeneous metric types and dispatches\n\
         // `eval`/`name` via `match` — zero vtable overhead.\n\
         //\n\
         // Also provides the `IntoFiniteEntries<T>` trait + per-arity impls so the\n\
         // `finite_score_set!` macro can stay a single arm (metrics tuple → trait\n\
         // dispatch), symmetric with `fixed_score_set!` / `Members`.\n\
         //\n\
         // Generated arities: 1–{max} (default feature `{default_level}`).\n\
         // Run `cargo run -p xtask -- gen --max <N>` to regenerate for higher arities.\n\
         // ---------------------------------------------------------------------------\n\
         \n\
         "
    ));

    // ---- finite_enum_inner! macro (enum + Scorable impl) ----
    content.push_str(
        r##"/// Generate a finite enum + `Scorable` impl for a given arity.
macro_rules! finite_enum_inner {
    ($name:ident; $($variant:ident $t:ident),+ $(,)?) => {
        #[allow(dead_code)]
        pub enum $name<$($t),+> {
            $($variant($t)),+
        }

        impl<T: $crate::Float, I, $($t: $crate::Scorable<T, I>),+>
            $crate::Scorable<T, I> for $name<$($t),+>
        {
            #[inline]
            fn eval(&self, input: &I) -> $crate::Witnessed<T, $crate::Value01> {
                match self {
                    $(Self::$variant(m) => m.eval(input)),+
                }
            }

            #[inline]
            fn name(&self) -> &str {
                match self {
                    $(Self::$variant(m) => m.name()),+
                }
            }
        }
    };
}

"##,
    );

    // ---- IntoFiniteEntries trait ----
    content.push_str(
        r##"/// Trait for converting a tuple of metrics into [`FiniteEnum`] entries.
///
/// This is the Finite-layer analogue of [`Members`](crate::Members): the
/// `finite_score_set!` macro expands to a tuple of metrics and delegates
/// to this trait for per-arity dispatch, avoiding hard-coded macro arms.
#[doc(hidden)]
pub trait IntoFiniteEntries<T: crate::Float> {
    /// The finite enum variant that wraps this tuple of metrics.
    type Enum;

    /// Consume the metric tuple and pair each metric with its weight from `weights`.
    fn into_finite_entries(self, weights: &[T]) -> Vec<(T, Self::Enum)>;
}

"##,
    );

    // ---- impl_into_finite_entries! macro ----
    content.push_str(
        r##"/// Internal helper: implement `IntoFiniteEntries<T>` for a tuple of arity 1+.
macro_rules! impl_into_finite_entries {
    ($Enum:ident; $($idx:tt $variant:ident $t:ident $v:ident),+ $(,)?) => {
        impl<T: $crate::Float, $($t),+> $crate::IntoFiniteEntries<T>
            for ($($t,)+)
        {
            type Enum = $Enum<$($t),+>;

            fn into_finite_entries(self, weights: &[T]) -> Vec<(T, Self::Enum)> {
                let ($($v,)+) = self;
                vec![
                    $((weights[$idx], $Enum::$variant($v)),)+
                ]
            }
        }
    };
}

"##,
    );

    // ---- per-arity: enum + IntoFiniteEntries impl ----
    for n in 1..=max {
        // finite_enum_inner! takes (variant, type_param)
        let enum_pairs: Vec<String> = (0..n).map(|i| format!("M{i} T{i}")).collect();
        let enum_joined = enum_pairs.join(", ");

        // impl_into_finite_entries! takes (idx, variant, type_param, var_binding)
        let into_pairs: Vec<String> = (0..n).map(|i| format!("{i} M{i} T{i} v{i}")).collect();
        let into_joined = into_pairs.join(", ");

        content.push_str(&format!(
            "// ---- arity {n} ----
#[cfg(feature = \"finite-enum-{n}\")]
finite_enum_inner!(FiniteEnum{n}; {enum_joined});
#[cfg(feature = \"finite-enum-{n}\")]
impl_into_finite_entries!(FiniteEnum{n}; {into_joined});\n\n"
        ));
    }

    // ---- free function (avoids trait-import in macro expansion) ----
    content.push_str(
        r##"/// Free-function wrapper so `finite_score_set!` can call
/// `$crate::into_finite_entries(tuple, weights)` without the caller
/// needing `IntoFiniteEntries` in scope.
#[doc(hidden)]
#[inline]
pub fn into_finite_entries<T: crate::Float, Tuple: crate::IntoFiniteEntries<T>>(
    tuple: Tuple,
    weights: &[T],
) -> Vec<(T, Tuple::Enum)> {
    Tuple::into_finite_entries(tuple, weights)
}
"##,
    );

    // Emit
    fs::write(&out_path, &content).unwrap_or_else(|e| {
        eprintln!("error writing {}: {e}", out_path.display());
        std::process::exit(1);
    });

    println!(
        "Generated {} with FiniteEnum1..FiniteEnum{max}, IntoFiniteEntries impls",
        out_path.display()
    );
}

fn default_level_for(max: usize) -> &'static str {
    if max <= 8 {
        "finite-level-8"
    } else if max <= 16 {
        "finite-level-16"
    } else if max <= 32 {
        "finite-level-32"
    } else if max <= 64 {
        "finite-level-64"
    } else {
        "finite-level-128"
    }
}
