use std::fs;

/// Generate `src/fixed_tuple.rs` — per-arity `Members` trait impls on flat member tuples.
///
/// Arity 1 is hand-written (macro_rules cannot reliably produce 1-tuples).
/// Arity 2+ uses the `impl_members_for_tuple!` helper macro.
pub fn generate(max: usize) {
    let out_dir = std::env::current_dir().unwrap();
    let out_path = out_dir.join("src").join("fixed_tuple.rs");

    assert!(max >= 1, "max must be >= 1");
    let default_level = default_level_for(max);
    let mut content = String::new();

    // ---- header ----
    content.push_str(&format!(
        "// @generated by xtask. Do not edit by hand.\n\
         // ---------------------------------------------------------------------------\n\
         // Per-arity implementations of the `Members` trait on flat member tuples.\n\
         //\n\
         // Arity 1 is hand-written (macro_rules cannot reliably produce 1-tuples).\n\
         // Arity 2+ uses the `impl_members_for_tuple!` helper macro.\n\
         //\n\
         // Generated arities: 1–{max} (default feature `{default_level}`).\n\
         // Run `cargo run -p xtask -- gen --max <N>` to regenerate for higher arities.\n\
         // ---------------------------------------------------------------------------\n\
         \n\
         use witnessed::WitnessExt;\n\
         \n\
         "
    ));

    // ---- arity 1 (hand-written) ----
    content.push_str(
        "// ---- arity 1 (hand-written: macro_rules cannot reliably produce 1-tuples) ----
#[cfg(feature = \"fixed-tuple-1\")]
impl<T: crate::Float, M0> crate::Members<T> for (crate::Member<T, M0>,) {
    type Raw = (crate::RawMember<T, M0>,);

    fn extract_raw_weights(raw: &Self::Raw) -> Vec<T> {
        vec![*raw.0.weight]
    }

    fn from_raw_with_weights(
        raw: Self::Raw,
        container: &witnessed::Witnessed<Vec<T>, crate::NormalizedContainer>,
    ) -> Self {
        (
            crate::Member {
                weight: container[0]
                    .witness()
                    .by(|v| {
                        crate::NormalizedWeight::from_normalized_container(*v, container)
                    })
                    .unwrap(),
                metric: raw.0.metric,
            },
        )
    }
}

",
    );

    // ---- helper macro for arity 2+ ----
    content.push_str(
        r##"/// Internal helper: implement `Members<T>` for a tuple of arity 2+.
macro_rules! impl_members_for_tuple {
    ($($idx:tt $name:ident),+) => {
        impl<T: $crate::Float, $($name),+> $crate::Members<T>
            for ($($crate::Member<T, $name>,)+)
        {
            type Raw = ($($crate::RawMember<T, $name>,)+);

            fn extract_raw_weights(raw: &Self::Raw) -> Vec<T> {
                vec![$(*raw.$idx.weight),+]
            }

            fn from_raw_with_weights(
                raw: Self::Raw,
                container: &witnessed::Witnessed<Vec<T>, $crate::NormalizedContainer>,
            ) -> Self {
                (
                    $($crate::Member {
                        weight: container[$idx]
                            .witness()
                            .by(|v| {
                                $crate::NormalizedWeight::from_normalized_container(
                                    *v, container,
                                )
                            })
                            .unwrap(),
                        metric: raw.$idx.metric,
                    },)+
                )
            }
        }
    };
}

"##,
    );

    // ---- per-arity impls for arities 2+ ----
    for n in 2..=max {
        let indices: Vec<String> = (0..n).map(|i| i.to_string()).collect();
        let names: Vec<String> = (0..n).map(|i| format!("M{i}")).collect();
        let pairs: Vec<String> = indices
            .iter()
            .zip(names.iter())
            .map(|(i, name)| format!("{i} {name}"))
            .collect();

        content.push_str(&format!(
            "// ---- arity {n} ----
#[cfg(feature = \"fixed-tuple-{n}\")]
impl_members_for_tuple!({pairs});\n\n",
            pairs = pairs.join(", ")
        ));
    }

    // Emit
    fs::write(&out_path, &content).unwrap_or_else(|e| {
        eprintln!("error writing {}: {e}", out_path.display());
        std::process::exit(1);
    });

    println!(
        "Generated {} with Members impl for arities 1–{max}",
        out_path.display()
    );
}

fn default_level_for(max: usize) -> &'static str {
    if max <= 8 {
        "fixed-level-8"
    } else if max <= 16 {
        "fixed-level-16"
    } else if max <= 32 {
        "fixed-level-32"
    } else if max <= 64 {
        "fixed-level-64"
    } else {
        "fixed-level-128"
    }
}
