use std::fs;

/// Generate `src/gen_score_set32.rs`:
/// 1. `impl_metric_tuple!` — helper macro for per-arity `MetricTuple32` impls
/// 2. Per-arity `MetricTuple32` impls (arity 1 hand-written, 2..=max via helper)
/// 3. `impl_scorer_builder_add!` — helper macro for per-arity `add()` methods
/// 4. Per-arity `add()` methods on `ScorerBuilder32` (0→1 hand-written, rest via helper)
///
/// The `MetricTuple32` trait, `ScoreSet32` trait, `Scorer32` struct, and
/// `ScorerBuilder32` struct live in `src/metric_f32.rs`.
pub fn generate(max: usize) {
    let out_dir = std::env::current_dir().unwrap();
    let out_path = out_dir.join("src").join("gen_score_set32.rs");

    assert!(max >= 1, "max must be >= 1");
    let mut content = String::new();

    // ---- header ----
    content.push_str(&format!(
        "// @generated by xtask. Do not edit by hand.\n\
         // ---------------------------------------------------------------------------\n\
         // Per-arity `MetricTuple32` impls + `ScorerBuilder32::add` methods.\n\
         //\n\
         // The trait and structs live in `src/metric_f32.rs`.\n\
         // Arity 1 is hand-written (macro_rules cannot reliably produce 1‑tuples).\n\
         // Arities 2–{max} use the `impl_metric_tuple!` helper macro,\n\
         // feature-gated behind `fixed-tuple-N`.  Default feature: `level-8`.\n\
         //\n\
         // Run `cargo run -p xtask -- gen --max <N>` to regenerate.\n\
         // ---------------------------------------------------------------------------\n\
         \n"
    ));

    // ---- 1. MetricTuple helper macro ----
    content.push_str(
        "/// Internal helper: implement `MetricTuple32<C>` for a tuple of arity 2+.\n\
         macro_rules! impl_metric_tuple {\n\
         \x20   ($($idx:tt $F:ident),+) => {\n\
         \x20       impl<C, $($F: Fn(&C) -> f32),+> crate::MetricTuple32<C>\n\
         \x20           for ($(crate::Metric32<C, $F>,)+)\n\
         \x20       {\n\
         \x20           fn weighted_sum(&self, weights: &[f32], ctx: &C) -> f32 {\n\
         \x20               0.0_f32 $(+ self.$idx.eval(ctx).map(|w| w.into_inner()).unwrap_or(0.0) * weights[$idx])+\n\
         \x20           }\n\
         \x20           fn collect_breakdown(\n\
         \x20               &self,\n\
         \x20               weights: &[f32],\n\
         \x20               ctx: &C,\n\
         \x20           ) -> alloc::vec::Vec<crate::Breakdown32> {\n\
         \x20               alloc::vec![\n\
         \x20                   $(self.$idx.make_breakdown(weights[$idx], ctx),)+\n\
         \x20               ]\n\
         \x20           }\n\
         \x20       }\n\
         \x20   };\n\
         }\n\
         \n",
    );

    // ---- 2. Per-arity MetricTuple impls ----
    content.push_str(
        "// ---- arity 1 (hand-written: macro_rules cannot reliably produce 1‑tuples) ----\n\
         #[cfg(feature = \"fixed-tuple-1\")]\n\
         impl<C, F0: Fn(&C) -> f32> crate::MetricTuple32<C> for (crate::Metric32<C, F0>,) {\n\
         fn weighted_sum(&self, weights: &[f32], ctx: &C) -> f32 {\n\
         self.0.eval(ctx).map(|w| w.into_inner()).unwrap_or(0.0) * weights[0]\n\
         }\n\
         fn collect_breakdown(\n\
         &self,\n\
         weights: &[f32],\n\
         ctx: &C,\n\
         ) -> alloc::vec::Vec<crate::Breakdown32> {\n\
         alloc::vec![self.0.make_breakdown(weights[0], ctx)]\n\
         }\n\
         }\n\
         \n",
    );

    for n in 2..=max {
        let pairs: Vec<String> = (0..n).map(|i| format!("{i} F{i}")).collect();
        content.push_str(&format!(
            "// ---- arity {n} ----\n\
             #[cfg(feature = \"fixed-tuple-{n}\")]\n\
             impl_metric_tuple!({});\n\
             \n",
            pairs.join(", ")
        ));
    }

    // ---- 3. ScorerBuilder add helper macro ----
    content.push_str(
        "/// Internal helper: implement `add()` on `ScorerBuilder32` for arity N → N+1.\n\
         macro_rules! impl_scorer_builder_add {\n\
         \x20   ($($idx:tt $F:ident),+) => {\n\
         \x20       impl<C, $($F: Fn(&C) -> f32),+> crate::ScorerBuilder32<C, ($(crate::Metric32<C, $F>,)+)>\n\
         \x20       {\n\
         \x20           /// Add the next metric with its raw weight.\n\
         \x20           pub fn add<F: Fn(&C) -> f32>(\n\
         \x20               mut self,\n\
         \x20               weight: f32,\n\
         \x20               metric: crate::Metric32<C, F>,\n\
         \x20           ) -> crate::ScorerBuilder32<C, ($(crate::Metric32<C, $F>,)+ crate::Metric32<C, F>,)> {\n\
         \x20               self.weights.push(weight);\n\
         \x20               crate::ScorerBuilder32 {\n\
         \x20                   metrics: ($(self.metrics.$idx,)+ metric,),\n\
         \x20                   weights: self.weights,\n\
         \x20                   _phantom: core::marker::PhantomData,\n\
         \x20               }\n\
         \x20           }\n\
         \x20       }\n\
         \x20   };\n\
         }\n\
         \n",
    );

    // ---- 4. Per-arity add() methods ----
    // Arity 0 → 1: hand-written (starting from (), not a tuple)
    content.push_str(
        "// ---- add: arity 0 → 1 (hand-written: starting from ()) ----\n\
         #[cfg(feature = \"fixed-tuple-1\")]\n\
         impl<C> crate::ScorerBuilder32<C, ()> {\n\
         /// Add the first metric with its raw weight.\n\
         pub fn add<F: Fn(&C) -> f32>(\n\
         mut self,\n\
         weight: f32,\n\
         metric: crate::Metric32<C, F>,\n\
         ) -> crate::ScorerBuilder32<C, (crate::Metric32<C, F>,)> {\n\
         self.weights.push(weight);\n\
         crate::ScorerBuilder32 {\n\
         metrics: (metric,),\n\
         weights: self.weights,\n\
         _phantom: core::marker::PhantomData,\n\
         }\n\
         }\n\
         }\n\
         \n",
    );

    // Arities N → N+1 for N = 1..max-1
    for n in 1..max {
        let pairs: Vec<String> = (0..n).map(|i| format!("{i} F{i}")).collect();
        let out_arity = n + 1;
        content.push_str(&format!(
            "// ---- add: arity {n} → {out_arity} ----\n\
             #[cfg(feature = \"fixed-tuple-{out_arity}\")]\n\
             impl_scorer_builder_add!({});\n\
             \n",
            pairs.join(", ")
        ));
    }

    fs::write(&out_path, &content).unwrap_or_else(|e| {
        eprintln!("error writing {}: {e}", out_path.display());
        std::process::exit(1);
    });

    println!(
        "Generated {} with MetricTuple32 impls for arities 1–{max} and ScorerBuilder32::add methods",
        out_path.display()
    );
}
