use std::fs;

/// Generate `src/gen_score_set32.rs`:
/// 1. `impl_score_set32!` — helper macro for per-arity trait impls
/// 2. Per-arity `ScoreSetTrait32` impls (arity 1 hand-written, 2..=max via helper)
/// 3. `score_set!` — single-arm macro
///
/// The `ScoreSetTrait32` trait and `Scored32` struct live in `src/metric_f32.rs`.
pub fn generate(max: usize) {
    let out_dir = std::env::current_dir().unwrap();
    let out_path = out_dir.join("src").join("gen_score_set32.rs");

    assert!(max >= 1, "max must be >= 1");
    let mut content = String::new();

    // ---- header ----
    content.push_str(&format!(
        "// @generated by xtask. Do not edit by hand.\n\
         // ---------------------------------------------------------------------------\n\
         // Per-arity `ScoreSetTrait32` impls + `score_set!` macro.\n\
         //\n\
         // The trait and `Scored32` struct live in `src/metric_f32.rs`.\n\
         // Arity 1 is hand-written (macro_rules cannot reliably produce 1‑tuples).\n\
         // Arities 2–{max} use the `impl_score_set32!` helper macro,\n\
         // feature-gated behind `fixed-tuple-N`.  Default feature: `level-8`.\n\
         //\n\
         // Run `cargo run -p xtask -- gen --max <N>` to regenerate.\n\
         // ---------------------------------------------------------------------------\n\
         \n"
    ));

    // ---- 1. Helper macro ----
    content.push_str(
        "/// Internal helper: implement `ScoreSetTrait32<C>` for a tuple of arity 2+.\n\
         macro_rules! impl_score_set32 {\n\
         \x20   ($($idx:tt $F:ident),+) => {\n\
         \x20       impl<C, $($F: Fn(&C) -> f32),+> crate::ScoreSetTrait32<C>\n\
         \x20           for ($(crate::Metric32<C, $F>,)+)\n\
         \x20       {\n\
         \x20           fn weighted_sum(&self, weights: &[f32], ctx: &C) -> f32 {\n\
         \x20               0.0_f32 $(+ self.$idx.eval(ctx).map(|w| w.into_inner()).unwrap_or(0.0) * weights[$idx])+\n\
         \x20           }\n\
         \x20           fn collect_breakdown(\n\
         \x20               &self,\n\
         \x20               weights: &[f32],\n\
         \x20               ctx: &C,\n\
         \x20           ) -> alloc::vec::Vec<crate::Breakdown32> {\n\
         \x20               alloc::vec![\n\
         \x20                   $(self.$idx.make_breakdown(weights[$idx], ctx),)+\n\
         \x20               ]\n\
         \x20           }\n\
         \x20       }\n\
         \x20   };\n\
         }\n\
         \n",
    );

    // ---- 2. Per-arity impls ----
    content.push_str(
        "// ---- arity 1 (hand-written: macro_rules cannot reliably produce 1‑tuples) ----\n\
         #[cfg(feature = \"fixed-tuple-1\")]\n\
         impl<C, F0: Fn(&C) -> f32> crate::ScoreSetTrait32<C> for (crate::Metric32<C, F0>,) {\n\
         fn weighted_sum(&self, weights: &[f32], ctx: &C) -> f32 {\n\
         self.0.eval(ctx).map(|w| w.into_inner()).unwrap_or(0.0) * weights[0]\n\
         }\n\
         fn collect_breakdown(\n\
         &self,\n\
         weights: &[f32],\n\
         ctx: &C,\n\
         ) -> alloc::vec::Vec<crate::Breakdown32> {\n\
         alloc::vec![self.0.make_breakdown(weights[0], ctx)]\n\
         }\n\
         }\n\
         \n",
    );

    for n in 2..=max {
        let pairs: Vec<String> = (0..n).map(|i| format!("{i} F{i}")).collect();
        content.push_str(&format!(
            "// ---- arity {n} ----\n\
             #[cfg(feature = \"fixed-tuple-{n}\")]\n\
             impl_score_set32!({});\n\
             \n",
            pairs.join(", ")
        ));
    }

    // ---- 3. score_set! macro ----
    content.push_str(
        "/// Combine heterogeneous metrics into a zero-vtable, zero-heap-allocation\n\
         /// weighted scorer.\n\
         ///\n\
         /// Each metric can have a different closure type.\n\
         ///\n\
         /// # Errors\n\
         /// Returns `Err` if any weight is not strictly positive (`> 0` and finite).\n\
         #[macro_export]\n\
         macro_rules! score_set32 {\n\
         \x20   ($($w:expr => $m:expr),+ $(,)?) => {{\n\
         \x20       let raw = [$($w as f32),+];\n\
         \x20       $crate::Scored32::new(($($m,)+), &raw)\n\
         \x20   }};\n\
         }\n",
    );

    fs::write(&out_path, &content).unwrap_or_else(|e| {
        eprintln!("error writing {}: {e}", out_path.display());
        std::process::exit(1);
    });

    println!(
        "Generated {} with ScoreSetTrait32 impls for arities 1–{max}",
        out_path.display()
    );
}
