use std::env;
use std::fs;
use std::process::Command;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("usage: xtask gen --max <N>");
        std::process::exit(1);
    }

    match args[1].as_str() {
        "gen" => {
            let max = args
                .get(3)
                .and_then(|s| s.parse::<usize>().ok())
                .unwrap_or(8);
            generate(max);
        }
        _ => {
            eprintln!("unknown command: {}", args[1]);
            std::process::exit(1);
        }
    }
}

fn generate(max: usize) {
    let out_dir = env::current_dir().unwrap();
    let out_path = out_dir.join("src").join("gen_tuple.rs");

    assert!(max >= 1, "max must be >= 1");
    let default_level = default_level_for(max);
    let mut content = String::new();

    // Header
    content.push_str(&format!(
        "// AUTO-GENERATED by xtask. Do not edit by hand.\n\
         // ---------------------------------------------------------------------------\n\
         // Per-arity implementations of the `Members` trait on flat member tuples.\n\
         //\n\
         // Arity 1 is hand-written (macro_rules cannot reliably produce 1-tuples).\n\
         // Arity 2+ uses the `impl_members_for_tuple!` helper macro.\n\
         //\n\
         // Generated arities: 1–{max} (default feature `{default_level}`).\n\
         // Run `cargo run -p xtask -- gen --max <N>` to regenerate for higher arities.\n\
         // ---------------------------------------------------------------------------\n\
         \n\
         use witnessed::WitnessExt;\n\
         \n\
         "
    ));

    // ---- arity 1 (hand-written) ----
    content.push_str(
        "// ---- arity 1 (hand-written: macro_rules cannot reliably produce 1-tuples) ----
#[cfg(feature = \"num-1\")]
impl<T: crate::ScoreFloat, M0> crate::Members<T> for (crate::Member<T, M0>,) {
    type Raw = (crate::RawMember<T, M0>,);

    fn extract_raw_weights(raw: &Self::Raw) -> Vec<T> {
        vec![raw.0.weight]
    }

    unsafe fn from_raw_with_weights(raw: Self::Raw, normalized: &[T]) -> Self {
        (
            crate::Member {
                weight: unsafe {
                    normalized[0].witness().by_unchecked::<crate::NormalizedWeight>()
                },
                metric: raw.0.metric,
            },
        )
    }
}

",
    );

    // Helper macro for arity 2+
    content.push_str(
        r##"/// Internal helper: implement `Members<T>` for a tuple of arity 2+.
macro_rules! impl_members_for_tuple {
    ($($idx:tt $name:ident),+) => {
        impl<T: $crate::ScoreFloat, $($name),+> $crate::Members<T>
            for ($($crate::Member<T, $name>,)+)
        {
            type Raw = ($($crate::RawMember<T, $name>,)+);

            fn extract_raw_weights(raw: &Self::Raw) -> Vec<T> {
                vec![$(raw.$idx.weight),+]
            }

            unsafe fn from_raw_with_weights(
                raw: Self::Raw,
                normalized: &[T],
            ) -> Self {
                (
                    $($crate::Member {
                        weight: unsafe {
                            normalized[$idx].witness().by_unchecked::<$crate::NormalizedWeight>()
                        },
                        metric: raw.$idx.metric,
                    },)+
                )
            }
        }
    };
}

"##,
    );

    // Per-arity impls for arities 2+
    for n in 2..=max {
        let indices: Vec<String> = (0..n).map(|i| i.to_string()).collect();
        let names: Vec<String> = (0..n).map(|i| format!("M{i}")).collect();
        let pairs: Vec<String> = indices
            .iter()
            .zip(names.iter())
            .map(|(i, name)| format!("{i} {name}"))
            .collect();

        content.push_str(&format!(
            "// ---- arity {n} ----\n\
             #[cfg(feature = \"num-{n}\")]\n\
             impl_members_for_tuple!({pairs});\n\n",
            pairs = pairs.join(", ")
        ));
    }

    // Emit
    fs::write(&out_path, &content).unwrap_or_else(|e| {
        eprintln!("error writing {}: {e}", out_path.display());
        std::process::exit(1);
    });

    // Format
    let fmt_status = Command::new("cargo")
        .args(["fmt", "--", out_path.to_str().unwrap()])
        .status()
        .unwrap_or_else(|e| {
            eprintln!("warning: cargo fmt failed on generated file: {e}");
            std::process::exit(1);
        });
    if !fmt_status.success() {
        eprintln!("warning: cargo fmt exited with non-zero status");
    }

    println!(
        "Generated {} with Members impl for arities 1–{max}",
        out_path.display()
    );
}

fn default_level_for(max: usize) -> &'static str {
    if max <= 8 {
        "level-8"
    } else if max <= 16 {
        "level-16"
    } else if max <= 32 {
        "level-32"
    } else if max <= 64 {
        "level-64"
    } else {
        "level-128"
    }
}
