use crate::erased::ErasedMetric;
use crate::float::Float;
use crate::value::{GtZero, NormalizedContainer, NormalizedWeight, Value01};
use core::marker::PhantomData;
use witnessed::{WitnessExt, Witnessed};

// ---------------------------------------------------------------------------
// EnumMember — a single weighted metric in an EnumScoreSet
// ---------------------------------------------------------------------------

/// A member of an [`EnumScoreSet`]: a normalized weight paired with a metric
/// enum variant.
///
/// See [`Member`](crate::Member) for the Layer-1 equivalent.
pub struct EnumMember<T: Float, E> {
    /// The normalized weight.
    pub weight: Witnessed<T, NormalizedWeight>,
    /// The metric enum variant.
    pub metric: E,
}

impl<T: Float, E> EnumMember<T, E> {
    /// Compute the weighted contribution of a metric score.
    ///
    /// `contribute(score) = score × normalized_weight`
    #[inline]
    pub fn contribute(&self, value: Witnessed<T, Value01>) -> T {
        value.into_inner() * self.weight.into_inner()
    }

    /// Return a reference to the metric.
    #[inline]
    pub fn metric(&self) -> &E {
        &self.metric
    }
}

// ---------------------------------------------------------------------------
// EnumScoreSet — weighted set with enum-based dispatch (Layer 2)
// ---------------------------------------------------------------------------

/// A weighted set of scoring operators using enum-based static dispatch.
///
/// `EnumScoreSet` stores a `Vec` of [`EnumMember`]s, each wrapping a variant
/// of a user-declared metric enum. At evaluation time, the enum's `eval`
/// method dispatches via `match` — zero vtable overhead for all non-`Custom`
/// variants.
///
/// Construct via [`EnumScoreSet::new`], then call [`.score()`](EnumScoreSet::score).
///
/// # Type parameters
///
/// - `T: Float` — the floating-point type (`f32` or `f64`).
/// - `I` — the input type passed to each metric.
/// - `E: ErasedMetric<T, I>` — the metric enum generated by
///   [`declare_metric_enum!`](crate::declare_metric_enum!).
///
/// # Example
///
/// ```ignore
/// let set = EnumScoreSet::<f64, &str, TestKind<f64, &str>>::new(vec![
///     (2.0, TestKind::AlwaysZero(ConstMetric::new("zero", 0.0))),
///     (3.0, TestKind::AlwaysOne(ConstMetric::new("one", 1.0))),
/// ])?;
///
/// let total = set.score(&"input");
/// // total = 0.4 * 0 + 0.6 * 1 = 0.6
/// ```
pub struct EnumScoreSet<T: Float, I, E> {
    members: Vec<EnumMember<T, E>>,
    _phantom: PhantomData<I>,
}

impl<T: Float, I, E: ErasedMetric<T, I>> EnumScoreSet<T, I, E> {
    /// Create a new `EnumScoreSet` from a list of `(weight, metric_enum)` pairs.
    ///
    /// Each weight must be finite and strictly positive. Weights are normalized
    /// to sum to 1.
    pub fn new(entries: Vec<(T, E)>) -> Result<Self, &'static str> {
        if entries.is_empty() {
            return Err("EnumScoreSet: must have at least one member");
        }

        // Validate all weights are > 0
        for (w, _) in &entries {
            GtZero::witness(*w)?;
        }

        let sum: T = entries.iter().fold(T::zero(), |acc, (w, _)| acc + *w);

        let mut normalized: Vec<T> = entries.iter().map(|(w, _)| *w / sum).collect();

        // Sort a copy for binary search in NormalizedWeight
        let mut sorted = normalized.clone();
        sorted.sort_by(|a, b| a.partial_cmp(b).unwrap_or(core::cmp::Ordering::Equal));
        let container = NormalizedContainer::witness(sorted)?;

        let members: Vec<EnumMember<T, E>> = entries
            .into_iter()
            .zip(normalized.drain(..))
            .map(|((_, metric), nw)| {
                let weight = nw
                    .witness()
                    .by(|v| NormalizedWeight::from_normalized_container(*v, &container))?;
                Ok(EnumMember { weight, metric })
            })
            .collect::<Result<Vec<_>, &'static str>>()?;

        Ok(EnumScoreSet {
            members,
            _phantom: PhantomData,
        })
    }

    /// Evaluate all metrics against `input` and sum their weighted contributions.
    ///
    /// This is the most common aggregation: each metric is evaluated, multiplied
    /// by its normalized weight, and summed.
    #[inline]
    pub fn score(&self, input: &I) -> T {
        self.members
            .iter()
            .fold(T::zero(), |acc, m| acc + m.contribute(m.metric.eval(input)))
    }

    /// Return the number of members in this set.
    #[inline]
    pub fn len(&self) -> usize {
        self.members.len()
    }

    /// Return `true` if the set has no members.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.members.is_empty()
    }

    /// Iterate over the members.
    #[inline]
    pub fn iter(&self) -> impl Iterator<Item = &EnumMember<T, E>> {
        self.members.iter()
    }
}

#[cfg(test)]
mod tests_for_enum_set;
