// AUTO-GENERATED by xtask. Do not edit by hand.
// ---------------------------------------------------------------------------
// Per-arity implementations of the `Members` trait on flat member tuples.
//
// Generated arities: 1–8 (default feature `level-8`).
// Run `cargo run --bin xtask -- gen --max <N>` to regenerate for higher arities.
// ---------------------------------------------------------------------------

/// Internal helper: implement `Members<T>` for a tuple of the given arity.
macro_rules! impl_members_for_tuple {
    ($($idx:tt $name:ident),+) => {
        impl<T: $crate::ScoreFloat, $($name),+> $crate::Members<T>
            for ($($crate::Member<T, $name>),+,)
        {
            type Raw = ($($crate::RawMember<T, $name>),+,);

            fn extract_raw_weights(raw: &Self::Raw) -> Vec<T> {
                vec![$(raw.$idx.weight),+]
            }

            unsafe fn from_raw_with_weights(
                raw: Self::Raw,
                normalized: &[T],
            ) -> Self {
                (
                    $($crate::Member {
                        weight: unsafe { $crate::NormalizedWeight::witness_unchecked(normalized[$idx]) },
                        metric: raw.$idx.metric,
                    }),+,
                )
            }
        }
    };
}

// ---- arity 1 ----
#[cfg(feature = "num-1")]
impl_members_for_tuple!(0 M0);

// ---- arity 2 ----
#[cfg(feature = "num-2")]
impl_members_for_tuple!(0 M0, 1 M1);

// ---- arity 3 ----
#[cfg(feature = "num-3")]
impl_members_for_tuple!(0 M0, 1 M1, 2 M2);

// ---- arity 4 ----
#[cfg(feature = "num-4")]
impl_members_for_tuple!(0 M0, 1 M1, 2 M2, 3 M3);

// ---- arity 5 ----
#[cfg(feature = "num-5")]
impl_members_for_tuple!(0 M0, 1 M1, 2 M2, 3 M3, 4 M4);

// ---- arity 6 ----
#[cfg(feature = "num-6")]
impl_members_for_tuple!(0 M0, 1 M1, 2 M2, 3 M3, 4 M4, 5 M5);

// ---- arity 7 ----
#[cfg(feature = "num-7")]
impl_members_for_tuple!(0 M0, 1 M1, 2 M2, 3 M3, 4 M4, 5 M5, 6 M6);

// ---- arity 8 ----
#[cfg(feature = "num-8")]
impl_members_for_tuple!(0 M0, 1 M1, 2 M2, 3 M3, 4 M4, 5 M5, 6 M6, 7 M7);
